---
- name: Create EC2 instance with ansible
  hosts: local
  connection: local
  tasks:
          - name: launch awsinstanceansible
            ec2:
                    key_name: awsk
                    instance_type: t2.micro
                    image: ami-052c08d70def0ac62
                    region: ap-south-1
                    wait: yes
                    count: 1
