---
- name: Install HTTPD package and enable the service
  hosts: all
  tasks:
    - name: Install the package
      yum:
        name: httpd
        state: present
    - name: Enable the service
      service:
        name: httpd
        state: present
        enabled: yes
