---
# vars file for roles/docker
install_docker_packages_redhat:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - docker-ce-3:18.09.1-3.el7
        - containerd.io
install_docker_packages_debian:
        - docker.io
        - apt-transport-https
        - curl
        - virtualenv
        - python3-setuptools
        - ca-certificates
        - software-properties-common
        - python3-pip
remove_docker_pakages_debian:
        - docker
        - docker-engine
        - docker.io
docker_service: docker
