---
# tasks file for roles/mysql
# This role will install MySQL and create db user and give permissions.
- name: Install Mysql package
  yum:
    name:
            - mysql-server
            - python3-PyMySQL
            - mysql-devel
            - gcc
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install Mysql package for Debian
  apt:
    name:
            - mysql-server
            - python-pip
            - python-mysqldb
            - mysql-common
    state: present
  when: ansible_os_family == 'Debian'

- name: Configure SELinux to start mysql on any port
  seboolean:
    name: mysql_connect_any
    state: true
    persistent: yes
  when: ansible_selinux.status == "enabled"

- name: Create Mysql configuration file
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf

- name: Start Mysqld Service
  service:
    name: mysqld
    state: started
    enabled: yes
  when: ansible_os_family == 'RedHat'

- name: Start Mysql Service
  service:
    name: mysql
    state: started
    enabled: yes
  when: ansible_os_family == 'Debian'

- name: Create Application Database
  mysql_db:
    name: testdb
    state: present

- name: Create Application DB User
  mysql_user:
    name: dbadmin
    password: dbadmin
    priv: "*.*:ALL"
    host: '%'
    state: present
  no_log: true
