---
# tasks file for roles/mysql
- include_tasks: setup_mysql_redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup_mysql_debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup_mysql_config.yml
