---
- name: Configure SELinux to start mysql on any port
  seboolean:
    name: mysql_connect_any
    state: true
    persistent: yes
  when: ansible_selinux.status == "enabled"

- name: Create Mysql configuration file
  template:
    src: "{{ mysql_template_cnf }}"
    dest: "{{ mysql_global_my_cnf }}"

- name: Create Application Database
  mysql_db: name=testdb state=present

- name: Create Application DB User
  mysql_user:
    name: "{{ mysql_user_name }}"
    password: "{{ mysql_user_password }}"
    priv: '*.*:ALL,GRANT'
    host: "{{ mysql_user_host }}"
    state: present
  no_log: "{{ mysql_nolog }}"
