---
# tasks file for roles/web
- include_tasks: setup_redhat_http.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup_debian_http.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup_configuration.yml
