---
# tasks file for roles/fi
- name: HTTP Package Installation
  yum:
          name: "{{ package }}"
          state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'        

- name: Install apache2 package
  apt: name=apache2 state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Start the HTTPD Service
  service:
          name: "{{ servicename }}"
          state: started
          enabled: yes

- name: Start the apache2 Service
  service:
          name: apache2
          state: started
          enabled: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Start the Firewalld Service
  service:
          name: firewalld
          state: started
          enabled: yes
          
- name: Enable Firewall Port for http
  firewalld:
          service: "{{ portnumber }}"
          permanent: true
          immediate: yes
          state: enabled
  notify:
          - reload firewall

- template:
        src: template.j2
        dest: /var/www/html/index.html

- name: Check the Web Page
  uri:
          url: http://{{ansible_default_ipv4.address}}
          return_content: yes
  register: http_verify
- debug: var=http_verify
