---
# tasks file for roles/fi
- name: HTTP Package Installation
  yum: name=httpd state=present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'        

- name: Install apache2 package
  apt: name=apache2 state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Start the HTTPD Service
  service:
          name: httpd
          state: started
          enabled: yes

- name: Start the apache2 Service
  service:
          name: apache2
          state: started
          enabled: yes

- name: Start the Firewalld Service
  service:
          name: firewalld
          state: started
          enabled: yes
          
- name: Enable Firewall Port for http
  firewalld:
          service: http
          permanent: true
          immediate: yes
          state: enabled
  notify:
          - reload firewall

- template:
        src: template.j2
        dest: /var/www/html/index.html
