---
- name: httpd Package Installation and start the service
  yum: name= "{{ package_install }}" state=present
  notify:
          - start httpd
          - start firewalld
          
- name: Enable firewall Port for http
  firewalld:
          service: "{{ rule }}"
          permanent: true
          immediate: true
          state: enabled
  notify:
          - reload firewall
