---
- name: Pull the docker images
  docker_image:
          name: nginx
          source: pull
- name: Create Default Container
  docker_container:
          name: testsite
          image: nginx
          state: started
