---
# tasks file for roles/docker
---
# tasks file for roles/web
- include_tasks: setup_docker_redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup_docker_debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup_configuration.yml

- import_tasks: docker.yml 
