---
# tasks file for roles/docker
- name: Add Docker Repository
  get_url:
          url: https://download.docker.com/linux/centos/docker-ce.repo
          dest: /etc/yum.repos.d/docker.repo
- name: Install the Depedency packages
  yum:
          name:
                  - yum-utils
                  - device-mapper-persistent-data
                  - lvm2
          state: present
  when: ansible_os_family == 'RedHat'

- name: Install the Docker Packages 1
  yum:
          name:
                  - docker-ce
                  - containerd.io
          state: present
  when: ansible_os_family == 'RedHat'

- name: Install PIP Modules
  pip:
          name: docker 

- name: Start the Docker service
  service:
          name: docker
          state: started
          enabled: yes

- name: Creating Docker User
  user:
          name: dkadmin
          groups: docker
          shell: /bin/bash
          state: present
          comment: "Docker User"
          password: 'dkadmin'

- import_tasks: docker.yml
