---
# tasks file for roles/fi
- name: Update the latest packages
  yum: name='*' state=latest exclude=docker*
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- name: Update the latest packages for Debian
  apt: upgrade=dist force_apt_get=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
