---
# tasks file for roles/fi
- name: Update the latest packages
  yum:
          name: '*'
          state: latest
  when: ansible_distrubution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- name: Update the latest packages for Debian
  apt:
          name: '*'
          state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
